version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry-network
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "service=registry"
        - "purpose=ci-cd"

networks:
  registry-network:
    driver: overlay
    attachable: true

volumes:
  registry_data:
    driver: local
