version: "3.8"

services:
  app:
    image: localhost:5000/swarm-lab-app:${VERSION:-latest}
    ports:
      - "3000:3000"
    networks:
      - dev-frontend
      - dev-backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_VERSION=${VERSION:-1.0.0}
      - LOG_LEVEL=debug
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "environment=dev"
        - "service=app"
        - "version=${VERSION:-1.0.0}"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  dev-frontend:
    external: true
  dev-backend:
    external: true
