version: "3.8"

services:
  app:
    image: localhost:5000/swarm-lab-app:${VERSION:-latest}
    ports:
      - "3001:3000"
    networks:
      - qa-frontend
      - qa-backend
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - APP_VERSION=${VERSION:-1.0.0}
      - LOG_LEVEL=info
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      labels:
        - "environment=qa"
        - "service=app"
        - "version=${VERSION:-1.0.0}"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s

networks:
  qa-frontend:
    external: true
  qa-backend:
    external: true
